package com.alekseivinogradov.celebrity.api.domain

const val LIST_FIRST_INDEX = 0
const val FIRST_PAGE = 1
const val ITEMS_PER_PAGE = 20
const val PAGING_PREFETCH_DISTANCE = 10
const val SEARCH_DEBOUNCE = 500L
const val PAGING_SUBMIT_LIST_DELAY = 10L
const val SWIPE_REFRESH_START_OFFSET = 45
const val SWIPE_REFRESH_END_OFFSET = 245
const val REPEAT_LISTENER_INITIAL_INTERVAL = 500L
const val REPEAT_LISTENER_REPEAT_INTERVAL = 200L
const val DEFAULT_ANIME_UPDATE_WORK_INTERVAL = 60L
